spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    database: mysql
    #show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/mer_qa?createDatabaseIfNotExist=true
    #url: jdbc:mysql://localhost:3306/mer?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    #username: mer
    #password: Mer#20230930!
    username: root
    password: Songuanda2501